version: '3.8'

services:
  cv-manager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CV_ManagerContext=Server=db;Database=CVManager;User=sa;Password=Your_password123;

  cvm-front:
    build:
      context: ./CVM-Front
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - cv-manager

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"