/**
 * TalentVault API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CvDto { 
    id?: number;
    createdAt?: string;
    updatedAt?: string;
    createdBy?: string | null;
    modifiedBy?: string | null;
    tenantId?: number;
    candidateName?: string | null;
    contentType?: string | null;
    metadata?: string | null;
    uploadedDate?: string;
    originalFileName?: string | null;
    downloadUrl?: string | null;
    textContent?: string | null;
    cvFile?: Blob | null;
}

