/**
 * TalentVault API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Location = 'Onsite' | 'Remote' | 'Hybrid';

export const Location = {
    Onsite: 'Onsite' as Location,
    Remote: 'Remote' as Location,
    Hybrid: 'Hybrid' as Location
};

