/**
 * TalentVault API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';


export interface CreateUserRequestDto { 
    username: string;
    password: string;
    firstname: string;
    lastname?: string | null;
    email: string;
    profilePictureUrl?: string | null;
    roles?: Role;
}
export namespace CreateUserRequestDto {
}


